"""Add cron_jobs table

Revision ID: 515dc63af583
Revises: 20250812_220030
Create Date: 2025-08-28 10:03:36.717329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515dc63af583'
down_revision = '20250812_220030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_files', schema=None) as batch_op:
        batch_op.alter_column('file_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_files', schema=None) as batch_op:
        batch_op.alter_column('file_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
