"""add shell fields to targets

Revision ID: 70b932ff82d8
Revises: 
Create Date: 2025-07-15 10:17:40.747834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b932ff82d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('update_nmap',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('update_dirsearch',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('update_wappalyzer',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('update_wpscan',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('update_pocs',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shell_type', sa.String(length=50), nullable=True, comment='Type of shell: bind/reverse/other'))
        batch_op.add_column(sa.Column('connect_time', sa.DateTime(), nullable=True, comment='Shell connect time (UTC)'))
        batch_op.add_column(sa.Column('disconnect_time', sa.DateTime(), nullable=True, comment='Shell disconnect time (UTC)'))
        batch_op.add_column(sa.Column('reconnect_count', sa.Integer(), nullable=True, comment='Number of reconnect attempts'))
        batch_op.add_column(sa.Column('last_status', sa.String(length=50), nullable=True, comment='Last known shell status'))
        batch_op.add_column(sa.Column('user', sa.String(length=100), nullable=True, comment='User of the shell session'))
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=True, comment='Original URL/hostname if applicable'))
        batch_op.alter_column('server_type',
               existing_type=sa.VARCHAR(length=18),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('incident_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.alter_column('incident_id',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('server_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=18),
               existing_nullable=False)
        batch_op.drop_column('url')
        batch_op.drop_column('user')
        batch_op.drop_column('last_status')
        batch_op.drop_column('reconnect_count')
        batch_op.drop_column('disconnect_time')
        batch_op.drop_column('connect_time')
        batch_op.drop_column('shell_type')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('update_pocs',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('update_wpscan',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('update_wappalyzer',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('update_dirsearch',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('update_nmap',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
